import env from './env.ts';

const constants = {
  NODE_ENV: env.NODE_ENV,
  PORT: env.PORT,
  GRAPHQL_SERVER_URL: env.GRAPHQL_SERVER_URL,
  NODEMAILER_SERVICE: env.NODEMAILER_SERVICE,
  NODEMAILER_HOST: env.NODEMAILER_HOST,
  NODEMAILER_PORT: env.NODEMAILER_PORT,
  NODEMAILER_SECURE: env.NODEMAILER_SECURE,
  NODEMAILER_EMAIL: env.NODEMAILER_EMAIL,
  NODEMAILER_PASSWORD: env.NODEMAILER_PASSWORD,
  NODEMAILER_NAME: env.NODEMAILER_NAME,
  PK: env.PK,
  ALCHEMY_API_KEY: env.ALCHEMY_API_KEY,
};

export default constants;
